<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <artifactId>rattan-plus-api</artifactId>
    <groupId>com.yiruantong</groupId>
    <version>${revision}</version>
  </parent>
  <dependencies>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.18.30</version>
    </dependency>
  </dependencies>
  <modelVersion>4.0.0</modelVersion>

  <modules>
    <module>rattan-basic</module>
    <module>rattan-generator</module>
    <module>rattan-job</module>
    <module>rattan-system</module>
    <module>rattan-inbound</module>
    <module>rattan-outbound</module>
    <module>rattan-inventory</module>
    <module>rattan-composite</module>
  </modules>

  <artifactId>rattan-modules</artifactId>
  <packaging>pom</packaging>

  <description>
    rattan-modules 业务模块
  </description>

</project>
