/**
 * 组件库
 * @description 组件库列表
 * @returns 返回组件库数据
 */
export const componentLibs: Array<any> = [
  {
    groupName: '基础组件',
    libs: [
      {
        type: 'rotationChart',
        icon: 'icon-zidingyibuju',
        title: '轮播图',
        items: [
          {
            image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/tiger-year/21-3.gif',
            title: '',
            url: '/pages/index',
            name: '测试标题2',
          },
          {
            image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/banner/banner01.jpg',
            title: '',
            url: '/pages/index',
            name: '测试标题1',
          },
          {
            image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/banner/banner03.png',
            title: '',
            url: '/pages/index',
            name: '测试标题2',
          },
        ],
        style: {
          bgBorderRadius: 0,
          bgMargin: 0,
          bgPadding: 3,
          maginTop: 0,
          bgColor1: 'rgba(255, 0, 0, 1)',
          bgColor2: 'rgba(255, 255, 255, 0.25)',
          indicatorStyle: 'circle',
          indicatorPosition: 'left',
          indicatorColor: 'rgba(255, 0, 106, 1)',
          imageBorderRadius: 5,
        },
      },
      {
        type: 'productList',
        icon: 'ele-Grid',
        title: '商品列表',
        templateType: '自动选择',
        auto: {
          typeId: [20758, 20760],
          orderBy: '综合',
          showCount: 5,
          productCount: 6,
          orderByType: 'DESC',
          orderByField: '综合',
        },
        custom: [
          {
            name: '',
            url: '',
          },
        ],
        common: {
          showTitle: true,
          showOriginPrice: true,
          showPrice: true,
          showCoupon: true,
        },
        style: {
          originPriceColor: 'rgba(144, 147, 153, 1)',
          salePriceColor: 'rgba(255, 0, 0, 1)',
          labelColor: 'rgba(0, 206, 209, 1)',
          titleColor: 'rgba(48, 49, 51, 1)',
          bgColor: 'rgba(242, 246, 252, 1)',
          maginTop: 0,
          bgPadding: 6,
          bgBorderRadius: 0,
          bgMargin: 0,
          productBgColor: 'rgba(255, 255, 255, 1)',
          productMaginTop: 7,
          productBorderRadius: 4,
          displayMode: '单列',
        },
      },
      {
        type: 'navGroup',
        icon: 'icon-liebiao6',
        title: '导航组',
        items: [
          {
            image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/tiger-year/41-6.png',
            title: '',
            url: '/pages/index',
            name: '领优惠券',
          },
          {
            image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/tiger-year/41-2.png',
            title: '',
            url: '',
            name: '我的收藏',
          },
          {
            image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/tiger-year/41-4.png',
            title: '',
            url: '',
            name: '我的推广',
          },
          {
            image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/tiger-year/41-10.png',
            title: '',
            url: '',
            name: '我的签到',
          },
          {
            image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/tiger-year/41-7.png',
            title: '',
            url: '',
            name: '秒杀活动',
          },
          {
            image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/tiger-year/41-8.png',
            title: '',
            url: '',
            name: '新闻资讯',
          },
          {
            image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/tiger-year/41-9.png',
            title: '',
            url: '',
            name: '拼团活动',
          },
          {
            image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/tiger-year/41-3.png',
            title: '',
            url: '',
            name: '积分商城',
          },
        ],
        style: {
          type: '多行展示',
          iconStyle: '方形',
          indicatorColor: 'rgba(232, 8, 124, 1)',
          bgPadding: 5,
          maginTop: 0,
          bgColor: 'rgba(255, 215, 0, 1)',
          lineCount: 2,
          bgStyle: '直角',
          iconSize: 50,
          bgMargin: 5,
          bgBorderRadius: 5,
          iconMargin: 15,
          fontSize: 14,
          showCount: 4,
          fontColor: 'rgba(96, 98, 102, 1)',
          indicatorStyle: 'none',
          moduleBorderWidth: null,
          moduleBgBorderRadius: null,
          moduleMarginTop: null,
          moduleMarginRight: null,
          moduleMarginBottom: null,
          moduleMarginLeft: null,
          modulePaddingTop: null,
          modulePaddingRight: null,
          modulePaddingBottom: null,
          modulePaddingLeft: null,
        },
        header: {
          width: null,
          height: null,
          fontSize: null,
          lineHeight: null,
          borderRadius: null,
          bgMargin: null,
          bgPadding: null,
        },
      },
      {
        type: 'newsList',
        icon: 'icon-liebiaolist46',
        title: '新闻列表',
        content: {
          rowCount: 4,
          module_Id: 4,
        },
        style: {
          itemMargin: 5,
          fontSize: 1,
          activeFontSize: 1,
          maxHeight: 350,
          bgColorDeg: 90,
          bgBorderRadius: 0,
          bgMargin: 5,
          bgPadding: 0,
          maginTop: 0,
          bgColor1: 'rgba(242, 246, 252, 1)',
          bgColor2: 'rgba(242, 246, 252, 1)',
          itemBorderRadius: 4,
          itemPadding: 5,
          itemBgColor: 'rgba(255, 255, 255, 1)',
        },
      },
      {
        type: 'newsBroadcast',
        icon: 'icon-liebiaolist29',
        title: '新闻播报',
        items: [
          {
            name: '新闻标题1',
            url: '',
          },
          {
            name: '新闻标题2',
            url: '',
          },
          {
            name: '新闻标题3',
            url: '',
          },
        ],
        style: {
          iconSize: 1,
          maginTop: 0,
          borderRadius: 0,
        },
        image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/tiger-year/31-1.png',
      },
      {
        type: 'promotionList',
        icon: 'icon-liebiao5',
        title: '促销列表',
        templateType: '自动选择',
        auto: {
          typeId: 20760,
          orderBy: '综合',
          showCount: 5,
          productCount: 6,
          orderByField: '综合',
          orderByType: 'DESC',
        },
        custom: [
          {
            name: '',
            url: '',
          },
        ],
        common: {
          showTitle: true,
          showOriginPrice: true,
          showPrice: true,
          showCoupon: true,
        },
        style: {
          showTitle: true,
          showOriginPrice: true,
          showPrice: true,
          showCoupon: true,
          productBorderRadius: 5,
          productMaginTop: 5,
          bgBorderRadius: 0,
          bgMargin: 0,
          bgPadding: 5,
          maginTop: 0,
          displayMode: '两列',
          bgColor: 'rgba(242, 246, 252, 1)',
          productBgColor: 'rgba(255, 255, 255, 1)',
          headerBorderRadius: 5,
          headerBgPadding: 5,
          headerBgMargin: 5,
          headerBgColor: 'rgba(255, 255, 255, 1)',
          headerTitleColor: 'rgba(96, 98, 102, 1)',
          headerTitleColorActive: 'rgba(255, 0, 0, 1)',
          headerBgColorActive: 'rgba(255, 0, 0, 1)',
          headerDescColorActive: 'rgba(255, 254, 254, 1)',
          headerDescColor: 'rgba(144, 147, 153, 1)',
        },
        items: [
          {
            image: '',
            title: '首发新品',
            url: 1,
            name: '1',
            desc: '最新出炉',
          },
          {
            image: '',
            title: '精品推荐',
            url: 2,
            name: '2',
            desc: '好物主推',
          },
          {
            title: '热门榜单',
            desc: '爱你所爱',
            url: 3,
          },
          {
            title: '促销单品',
            desc: '超值优选',
            url: 4,
          },
        ],
      },
      {
        type: 'productType',
        icon: 'icon-liebiao3',
        title: '商品分类',
        items: [
          {
            title: '精选',
            url: '',
            isDefault: true,
          },
          {
            image: '',
            title: '靓丽美妆',
            url: '',
            isDefault: false,
          },
          {
            image: '',
            title: '母婴',
            url: '',
            isDefault: false,
          },
          {
            image: '',
            title: '珠宝饰品',
            url: '',
            isDefault: false,
          },
          {
            image: '',
            title: '男装',
            url: '',
            isDefault: false,
          },
          {
            image: '',
            title: '食品',
            url: '',
            isDefault: false,
          },
        ],
        style: {
          itemMargin: 20,
          fontSize: 12,
          activeFontSize: 12,
          bgBorderRadius: 0,
          bgMargin: 0,
          bgPadding: 8,
          maginTop: 0,
          bgColorDeg: 90,
          bgColor1: 'rgba(255, 0, 0, 1)',
          bgColor2: 'rgba(255, 0, 0, 1)',
          fontColor: 'rgba(255, 255, 255, 1)',
          activeFontColor: 'rgba(255, 0, 0, 1)',
          activeBgColor: 'rgba(255, 255, 255, 1)',
          activeBgBorderRadius: 3,
          activeBgPadding: 4,
          activeBgPadding2: 7,
          activeBgPadding1: 0,
        },
      },
      {
        type: 'imageMagic',
        icon: 'icon-credentials_icon',
        title: '图片魔方',
        items: {
          item1: {
            name: '',
            url: '',
            image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/product/p11.jpg',
          },
          item2: {
            name: '',
            url: '',
            image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/product/p03.jpg',
          },
          item3: {
            name: '',
            url: '',
            image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/product/p15.jpg',
          },
          item4: {
            name: '',
            url: '',
            image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/product/p19.jpg',
          },
          item5: {
            name: '',
            url: '',
            image: '',
          },
          item6: {
            name: '',
            url: '',
            image: '',
          },
        },
        style: {
          iconSize: 1,
          iconMargin: 1,
          fontSize: 1,
          bgBorderRadius: 0,
          bgMargin: 0,
          bgPadding: 8,
          maginTop: 0,
          type: 4,
          bgColor: 'rgba(242, 246, 252, 1)',
          imageMargin: 5,
          imageBorderRadius: 4,
        },
      },
      {
        type: 'searchBox',
        icon: 'yrt-danhangshurukuang',
        title: '搜索框',
        items: [
          {
            name: '香水',
          },
          {
            image: '',
            title: '',
            url: '',
            name: '美食',
          },
        ],
        style: {
          bgColor: 'rgba(255, 0, 0, 1)',
          bgPadding: 0,
          maginTop: 0,
        },
        image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/other/logo.png',
      },
      {
        type: 'userCenter',
        icon: 'icon-ren',
        title: '用户中心',
        items: [
          {
            name: '香水',
          },
          {
            image: '',
            title: '',
            url: '',
            name: '美食',
          },
        ],
        style: {
          bgColor: 'rgba(255, 0, 0, 1)',
          bgPadding: 0,
          maginTop: 0,
        },
        image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/other/logo.png',
      },
    ],
  },
  {
    groupName: '营销组件',
    libs: [
      {
        icon: 'icon-biaodan',
        title: '砍价',
        type: 'bargaining',
        auto: {
          typeId: 20760,
          orderBy: '综合',
          showCount: 5,
          productCount: null,
        },
        custom: [
          {
            name: '',
            url: '',
          },
        ],
        common: {
          showTitle: true,
          showOriginPrice: true,
          showPrice: true,
          showCoupon: true,
        },
        style: {
          showTitle: true,
          showOriginPrice: true,
          showPrice: true,
          showCoupon: true,
          productBorderRadius: 0,
          productMaginTop: 5,
          bgBorderRadius: 0,
          bgMargin: 0,
          bgPadding: 5,
          maginTop: 0,
          displayMode: '单列',
          bgColor: 'rgba(242, 246, 252, 1)',
          productBgColor: 'rgba(255, 255, 255, 1)',
        },
        header: {
          width: 22,
          height: 22,
          fontSize: null,
          borderRadius: null,
          bgMargin: null,
          bgPadding: 5,
          image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/icon/11.gif',
          title: '砍价活动',
          showMore: true,
        },
      },
      {
        icon: 'icon-siweidaotu',
        title: '优惠券',
        type: 'coupon',
        items: [
          {
            desc: '满100可用',
            money: 50,
            url: '',
          },
          {
            desc: '满300可用',
            money: '150',
            url: '',
          },
          {
            desc: '满200可用',
            money: '100',
            url: '',
          },
        ],
        style: {
          itemMargin: 10,
          fontSize: 1,
          itemBorderRadius: 5,
          bgBorderRadius: 0,
          bgMargin: 0,
          bgPadding: 5,
          maginTop: 0,
          itemBgColor: 'rgba(255, 69, 0, 1)',
          fontColor: 'rgba(255, 255, 255, 1)',
          bgColor: 'rgba(242, 246, 252, 1)',
        },
      },
      {
        icon: 'icon-jinridaiban',
        title: '活动魔方',
        type: 'marketingMagic',
        auto: {
          typeId: 20760,
          orderBy: '综合',
          showCount: 5,
          productCount: 1,
          orderByField: '综合',
          orderByType: 'DESC',
        },
        custom: [
          {
            name: '',
            url: '',
          },
        ],
        common: {
          showTitle: true,
          showOriginPrice: true,
          showPrice: true,
          showCoupon: true,
        },
        style: {
          showTitle: true,
          showOriginPrice: true,
          showPrice: true,
          showCoupon: true,
          productBorderRadius: 5,
          productMaginTop: 5,
          bgBorderRadius: 0,
          bgMargin: 0,
          bgPadding: 5,
          maginTop: 0,
          displayMode: '两列2',
          bgColor: 'rgba(255, 229, 227, 1)',
          productBgColor: 'rgba(255, 255, 255, 1)',
        },
        header: {
          width: 22,
          height: 22,
          fontSize: 16,
          borderRadius: 0,
          bgMargin: 0,
          bgPadding: 5,
          image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/icon/10.gif',
          title: '超值爆款',
          showMore: false,
          bgColor: 'rgba(255, 229, 227, 1)',
          subTitle: '美好生活由此开始',
          color: 'rgba(255, 0, 0, 1)',
          fill: 'fill',
          fit: 'contain',
        },
        items: [
          {
            title: '今日推荐',
            desc: '店主诚意推荐 品质商品',
            url: '',
            image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/product/p05.jpg',
          },
          {
            title: '热门榜单',
            desc: '店主诚意推荐 品质商品',
            url: '',
            image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/product/p13.jpg',
          },
          {
            title: '首发新品',
            desc: '新品上架等了您来拿',
            url: '',
            image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/product/p15.jpg',
          },
          {
            title: '促销单品',
            desc: '综合评选好产品',
            url: '',
            image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/product/p16.jpg',
          },
        ],
      },
      {
        icon: 'icon-gerenzhongxin',
        title: '拼团',
        type: 'combination',
        auto: {
          typeId: 20760,
          orderBy: '综合',
          showCount: 5,
          productCount: 3,
        },
        custom: [
          {
            name: '',
            url: '',
          },
        ],
        common: {
          showTitle: true,
          showOriginPrice: true,
          showPrice: true,
          showCoupon: true,
        },
        style: {
          showTitle: true,
          showOriginPrice: true,
          showPrice: true,
          showCoupon: true,
          productBorderRadius: 0,
          productMaginTop: 5,
          bgBorderRadius: 0,
          bgMargin: 0,
          bgPadding: 5,
          maginTop: 0,
          displayMode: '单列',
          bgColor: 'rgba(242, 246, 252, 1)',
          productBgColor: 'rgba(255, 255, 255, 1)',
        },
        header: {
          width: 22,
          height: 22,
          fontSize: 0,
          borderRadius: 0,
          bgMargin: 0,
          bgPadding: 5,
          image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/icon/11.gif',
          title: '拼团活动',
          showMore: true,
        },
      },
      {
        icon: 'icon-shenqingkaiban',
        title: '秒杀',
        type: 'seckill',
        auto: {
          typeId: 20760,
          orderBy: '综合',
          showCount: 5,
          productCount: null,
        },
        custom: [
          {
            name: '',
            url: '',
          },
        ],
        common: {
          showTitle: true,
          showOriginPrice: true,
          showPrice: true,
          showCoupon: true,
        },
        style: {
          showTitle: true,
          showOriginPrice: true,
          showPrice: true,
          showCoupon: true,
          productBorderRadius: 0,
          productMaginTop: 5,
          bgBorderRadius: 0,
          bgMargin: 0,
          bgPadding: 5,
          maginTop: 0,
          displayMode: '单列',
          bgColor: 'rgba(242, 246, 252, 1)',
          productBgColor: 'rgba(255, 255, 255, 1)',
        },
        header: {
          width: 22,
          height: 22,
          fontSize: null,
          borderRadius: null,
          bgMargin: null,
          bgPadding: 5,
          image: 'https://auod-beijing.oss-cn-beijing.aliyuncs.com/bbc/icon/11.gif',
          title: '秒杀活动',
          showMore: true,
        },
      },
      {
        icon: 'icon-zujian',
        title: '小程序直播',
      },
    ],
  },
  {
    groupName: '工具组件',
    libs: [
      {
        icon: 'icon-bangzhu1',
        title: '在线客服',
      },
      {
        type: 'titleHeader',
        icon: 'icon-iconfontcolor32',
        title: '标题',
        content: {
          image: '',
          title: '标题',
          url: '',
        },
        style: {
          bgPadding: 5,
          borderRadius: null,
          bgMargin: null,
          maginTop: null,
          fontSize: 14,
        },
      },
      {
        type: 'guideBlank',
        icon: 'icon-msnui-info',
        title: '辅助空白',
        style: {
          height: 10,
          bgColor: 'rgba(248, 248, 248, 1)',
        },
      },
      {
        type: 'guideLine',
        icon: 'icon-hebingumerger',
        title: '辅助线',
        style: {
          bgColor: 'rgba(242, 246, 252, 1)',
          lineColor: 'rgba(220, 223, 230, 1)',
          height: 10,
          bgMargin: 5,
          maginTop: 0,
          bgPadding: 0,
          borderStyle: 'dashed',
        },
        desc: '',
      },
      {
        icon: 'icon-fuwenbenkuang',
        title: '富文本',
      },
      {
        icon: 'icon-tuihuo3',
        title: '关注公众号',
      },
    ],
  },
  {
    groupName: 'uViewUI组件',
    libs: [
      {
        type: 'u-input',
        icon: 'icon-iconfontcolor32',
        title: '输入框',
        label: '输入框',
        prop: null,
        placeholder: null,
        style: {
          bgPadding: 5,
          borderRadius: null,
          bgMargin: null,
          maginTop: null,
          fontSize: 14,
        },
        key: 'u-input',
      },
      {
        type: 'u-text',
        icon: 'icon-hebingumerger',
        title: '静态文本',
        label: '静态文本',
        dataType: 'string',
        prop: null,
        style: {
          bgColor: null,
          lineColor: 'rgba(220, 223, 230, 1)',
          height: 10,
          bgMargin: 0,
          maginTop: 0,
          bgPadding: 0,
          borderStyle: 'dashed',
        },
        key: 'u-text',
      },
      {
        type: 'u-picker',
        icon: 'icon-msnui-info',
        title: '选择器',
        options: {
          label: '选择器',
          prop: null,
          placeholder: '',
          showLabel: true,
          remote: 'bindDropdown',
          options: [
            {
              value: '新选项1',
              label: '新选项1',
            },
            {
              value: '新选项2',
              label: '新选项2',
            },
            {
              value: '新选项3',
              label: '新选项3',
            },
          ],
          props: {
            label: null,
            value: null,
          },
        },
        style: {
          bgColor: null,
          lineColor: null,
          height: 10,
          bgMargin: 5,
          maginTop: 0,
          bgPadding: 0,
          borderStyle: 'dashed',
        },
        key: 'u-picker',
      },
      {
        type: 'u-datetime-picker',
        icon: 'icon-iconfontcolor32',
        title: '日期选择器',
        label: '日期',
        prop: null,
        placeholder: null,
        style: {
          bgPadding: 5,
          borderRadius: null,
          bgMargin: null,
          maginTop: null,
          fontSize: 14,
        },
        key: 'u-upload',
      },
      {
        type: 'u-radio',
        icon: 'icon-danxuan',
        title: '单选框',
        label: '单选框',
        prop: null,
        placeholder: null,
        style: {
          bgPadding: 5,
          borderRadius: null,
          bgMargin: null,
          maginTop: null,
          fontSize: 14,
        },
        radioOptions: [
          {
            value: '新选项1',
            label: '新选项1',
          },
        ],
        inline: false,
        key: 'u-radio',
      },
      {
        type: 'u-content',
        icon: 'icon-biaoti',
        title: '提示语',
        content: '提示语',
        placeholder: null,
        style: {
          bgPadding: 5,
          borderRadius: null,
          bgMargin: null,
          maginTop: null,
          fontSize: 16,
        },
        key: 'u-content',
      },
      {
        type: 'u-upload',
        title: '图片/文件',
        icon: 'icon-tupian',
        options: {
          label: '图片/文件',
          width: '80px',
          height: '80px',
          serverAction: '/api/common/upload',
          disabled: false,
          maxCount: 3,
          multiple: true,
          listType: 'picture-card',
          noLabel: false, // 无标题
        },
        style: {},
        key: 'u-datetime-picker',
      },
    ],
  },
  {
    groupName: '布局组件',
    libs: [
      {
        type: 'u-grid',
        title: '栅格布局',
        icon: 'icon-saomiaoerweima',
        columns: [
          {
            span: 12,
            fields: [],
          },
          {
            span: 12,
            fields: [],
          },
        ],
        options: {
          gutter: 2,
          justify: 'start',
          align: 'top',
        },
        style: {
          bgColor: 'rgba(248, 248, 248, 1)',
        },
      },
      {
        type: 'u-detail',
        title: '明细布局',
        icon: 'icon-liebiao2',
        fields: [],
        options: {
          size: 'mini',
          pageIndex: 1,
          pageSize: 50,
          detailSelections: [],
          idField: null,
        },
        buttons: [],
        style: {},
      },
      {
        type: 'u-splitter',
        title: '分割标题',
        icon: 'icon-biaoti',
        label: '分割标题',
        align: 'left',

        style: {},
      },
      {
        type: 'u-button',
        title: '按钮',
        icon: 'icon-anniu',
        options: {
          label: '按钮',
          authNode: null, // 权限点名称
          type: 'primary',
          width: null,
        },
        style: {},
      },
    ],
  },
  {
    groupName: 'PC组件',
    libs: [
      {
        type: 'pcStat',
        icon: 'icon-biaoti',
        title: '统计信息',
        api: {},
        search: {},
        header: {
          bgColor: 'rgba(255, 255, 255, 1)',
          fontSize: '18px',
          text: '库存预警',
          textAlign: 'left',
          padding: '5px 5px 10px',
          borderBottom: '1px solid #efefef',
          margin: '0px 0 10px',
        },
        style: {
          bgColor: null,
          bgMargin: null,
          fontSize: 14,
          maginTop: null,
          bgPadding: '0',
          boxShadow: true,
          borderRadius: 5,
          innerBgColor: null,
          innerBorderColor: null,
          innerBorderStyle: 'solid',
          innerBorderWidth: 1,
        },
        columns: [
          {
            span: 6,
            field: {
              icon: 'fa fa-meetup',
              num1: 3615,
              num2: 0.1234,
              title: '月度计划信息',
              padding: '10px',
              iconColor: 'rgba(64, 158, 255, 1)',
              iconWidth: 60,
              num2Color: 'rgba(64, 158, 255, 1)',
              iconHeight: 60,
              iconPadding: 10,
              iconFontSize: 30,
              iconBorderRadius: 40,
              iconBackgroundColor: 'rgba(64, 158, 255, 0.29)',
              backgroundColor: 'rgba(54, 124, 234, 0.08)',
              borderWidth: 1,
              borderColor: 'rgba(64, 158, 255, 1)',
              borderStyle: 'solid',
              borderRadius: 5,
            },
          },
          {
            span: 6,
            field: {
              icon: 'fa fa-calendar',
              num1: 3615,
              num2: 0.1234,
              title: '月度计划信息',
              padding: '10px',
              iconColor: 'rgba(208, 3, 208, 1)',
              iconWidth: 60,
              num2Color: 'rgba(208, 3, 208, 1)',
              iconHeight: 60,
              iconPadding: 10,
              iconFontSize: 30,
              iconBorderRadius: 40,
              iconBackgroundColor: 'rgba(208, 3, 208, 0.45)',
              backgroundColor: 'rgba(208, 3, 208, 0.05)',
              borderWidth: 1,
              borderColor: 'rgba(252, 68, 252, 1)',
              borderStyle: 'solid',
              borderRadius: 5,
            },
          },
          {
            span: 6,
            field: {
              icon: 'fa fa-podcast',
              num1: 3523,
              num2: 0.1234,
              title: '年度计划信息',
              padding: '10px',
              iconColor: 'rgba(255, 0, 0, 1)',
              iconWidth: 60,
              num2Color: '#FF6462',
              iconHeight: 60,
              iconPadding: 10,
              iconFontSize: 34,
              iconBorderRadius: 40,
              iconBackgroundColor: 'rgba(255, 0, 0, 0.3)',
              backgroundColor: 'rgba(255, 69, 0, 0.11)',
              borderColor: 'rgba(255, 69, 0, 1)',
              borderWidth: 1,
              borderStyle: 'solid',
              borderRadius: 5,
            },
          },
          {
            span: 6,
            field: {
              icon: 'fa fa-line-chart',
              num1: 2362,
              num2: 0.1234,
              title: '访问统计信息',
              padding: '10px',
              iconColor: 'rgba(5, 200, 5, 1)',
              iconWidth: 60,
              num2Color: 'rgba(5, 200, 5, 1)',
              iconHeight: 60,
              iconPadding: 10,
              iconFontSize: 30,
              iconBorderRadius: 40,
              iconBackgroundColor: 'rgba(5, 200, 5, 0.35)',
              backgroundColor: 'rgba(255, 215, 0, 0.08)',
              borderColor: 'rgba(255, 215, 0, 1)',
              borderStyle: 'solid',
              borderWidth: 1,
              borderRadius: 5,
            },
          },
        ],
        options: {
          align: 'top',
          gutter: 10,
          justify: 'start',
        },
      },
      {
        type: 'pcNav',
        icon: 'icon-liebiao6',
        title: '模块导航',
        api: {},
        search: {},
        header: {},
        items: [
          {
            url: '/inbound/in/order',
            icon: 'iconfont icon-zhongduancanshuchaxun',
            name: '预到货单',
            iconColor: 'rgba(64, 158, 255, 1)',
          },
          {
            url: '/inbound/scan/order',
            icon: 'iconfont icon-AIshiyanshi',
            name: '扫描入库',
            iconColor: 'rgba(208, 3, 208, 1)',
          },
          {
            url: '/inbound/in/enter',
            icon: 'iconfont icon-dingdan2',
            name: '入库记录',
            iconColor: 'rgba(0, 186, 189, 1)',
          },
          {
            url: '/inbound/in/shelve',
            icon: 'iconfont icon-xingqiu',
            name: '上架记录',
            iconColor: 'rgba(255, 0, 0, 1)',
          },
          {
            url: '/outbound/out/order',
            icon: 'iconfont icon-zidingyibuju',
            name: '出库订单',
            iconColor: 'rgba(64, 158, 255, 1)',
          },
          {
            url: '/outbound/out/create-order-batch',
            icon: 'iconfont icon-niantie',
            name: '生成波次',
            iconColor: 'rgba(5, 200, 5, 1)',
          },
          {
            url: '/outbound/scan/order-picking',
            icon: 'iconfont icon-dunhuo',
            name: '拣货下架',
            iconColor: 'rgba(255, 140, 0, 1)',
          },
          {
            url: '/outbound/scan/order-picking',
            icon: 'iconfont icon-shidu',
            name: '打包校验',
            iconColor: 'rgba(64, 158, 255, 1)',
          },
          {
            url: '/outbound/scan/order-picking',
            name: '打包校验2',
            iconColor: 'rgba(255, 0, 0, 1)',
            icon: 'iconfont icon-bolangneng',
          },
        ],
        style: {
          type: '多行展示',
          iconStyle: '方形',
          indicatorColor: 'rgba(232, 8, 124, 1)',
          bgPadding: 5,
          maginTop: 0,
          bgColor: 'rgba(255, 215, 0, 1)',
          lineCount: 2,
          bgStyle: '直角',
          iconSize: 50,
          bgMargin: 5,
          bgBorderRadius: 5,
          iconMargin: 15,
          fontSize: 14,
          showCount: 4,
          fontColor: 'rgba(96, 98, 102, 1)',
          indicatorStyle: 'none',
          moduleBorderWidth: null,
          moduleBgBorderRadius: null,
          moduleMarginTop: null,
          moduleMarginRight: null,
          moduleMarginBottom: null,
          moduleMarginLeft: null,
          modulePaddingTop: null,
          modulePaddingRight: null,
          modulePaddingBottom: null,
          modulePaddingLeft: null,
        },
      },
      {
        type: 'pcStatAll',
        icon: 'icon-tuichuquanping',
        title: '高级统计信息',
        api: {},
        search: {},
        header: {
          text: '高级统计信息',
          fontSize: '18px',
          borderBottom: '1px solid #efefef',
          padding: '5px 5px 10px',
          margin: '0px 0 10px',
        },
        content: {
          num1: 12512,
          num2: 0.1234,
          title: '订单统计信息',
          icon: 'fa fa-meetup',
          iconFontSize: 42,
          num2Color: '#FF6462',
          iconColor: 'rgba(64, 158, 255, 1)',
          iconBackgroundColor: 'rgba(64, 158, 255, 0.35)',
          iconBorderRadius: 40,
          iconPadding: 10,
          iconWidth: 60,
          iconHeight: 60,
        },
        style: {
          bgColor: null,
          bgMargin: null,
          fontSize: 14,
          maginTop: null,
          bgPadding: '0 16px 10px',
          boxShadow: true,
          borderRadius: 5,
          innerBgColor: 'rgba(255, 255, 255, 1)',
          innerBorderColor: 'rgba(241, 242, 243, 1)',
          innerBorderStyle: 'solid',
          innerBorderWidth: 1,
        },
        columns: [
          {
            name: '库存概况',
            rows: [
              {
                value: '584吨',
                title: '库存重量',
                titleColor: '#010101',
                valueColor: 'rgba(255, 0, 0, 1)',
                titleFontSize: '14',
                valueFontSize: 14,
              },
              {
                value: '1549989元',
                title: '库存金额',
                titleColor: '#010101',
                valueColor: 'rgba(5, 200, 5, 1)',
                titleFontSize: 14,
                valueFontSize: 14,
              },
              {
                value: '6548',
                title: '缺货数量',
                titleColor: '#010101',
                valueColor: '#ff0000',
                titleFontSize: 14,
                valueFontSize: 14,
              },
              {
                value: '1323',
                title: '滞销数量',
                titleColor: '#010101',
                valueColor: '#ff0000',
                titleFontSize: 14,
                valueFontSize: 14,
              },
            ],
            subName: '',
            subName1: '56958',
            subName2: '',
            nameColor: 'rgba(96, 98, 102, 1)',
            nameFontSize: '22px',
            subName1Color: 'rgba(199, 21, 133, 1)',
            subName2Color: 'rgba(255, 0, 0, 1)',
            subName1FontSize: '20px',
            subName2FontSize: '18px',
          },
          {
            name: '待处理单据',
            rows: [
              {
                value: '100',
                title: '待入库单据',
                titleColor: '#010101',
                valueColor: '#ff0000',
                titleFontSize: 14,
                valueFontSize: 14,
              },
              {
                value: '30',
                title: '待上架单据',
                titleColor: '#010101',
                valueColor: 'rgba(5, 200, 5, 1)',
                titleFontSize: 14,
                valueFontSize: 14,
              },
              {
                value: '100',
                title: '待拣货单据',
                titleColor: '#010101',
                valueColor: '#ff0000',
                titleFontSize: 14,
                valueFontSize: 14,
              },
              {
                value: '5',
                title: '待出库单据',
                titleColor: '#010101',
                valueColor: '#ff0000',
                titleFontSize: 14,
                valueFontSize: 14,
              },
            ],
            subName1: '235',
            subName2: '',
            nameFontSize: '22px',
            subName1Color: 'rgba(199, 21, 133, 1)',
            subName1FontSize: '20px',
            subName2FontSize: '18px',
          },
          {
            name: '入库概况',
            rows: [
              {
                value: '125',
                title: '今日入库单据',
                titleColor: '#010101',
                valueColor: '#ff0000',
                titleFontSize: 14,
                valueFontSize: 14,
              },
              {
                value: '236',
                title: '昨日入库单据',
                titleColor: '#010101',
                valueColor: '#ff0000',
                titleFontSize: 14,
                valueFontSize: 14,
              },
              {
                value: '56吨',
                title: '入库重量',
                titleColor: '#010101',
                valueColor: '#ff0000',
                titleFontSize: 14,
                valueFontSize: 14,
              },
              {
                value: '123468',
                title: '入库金额',
                titleColor: '#010101',
                valueColor: '#ff0000',
                titleFontSize: 14,
                valueFontSize: 14,
              },
            ],
            subName1: '41268',
            subName2: '',
            nameFontSize: '22px',
            subName1FontSize: '20px',
            subName2FontSize: '',
          },
          {
            name: '出库概况',
            rows: [
              {
                value: '241',
                title: '今日出库单据',
                titleColor: '#010101',
                valueColor: '#ff0000',
                titleFontSize: 14,
                valueFontSize: 14,
              },
              {
                value: '158',
                title: '昨日出库单据',
                titleColor: '#010101',
                valueColor: '#ff0000',
                titleFontSize: 14,
                valueFontSize: 14,
              },
              {
                value: '68吨',
                title: '出库重量',
                titleColor: '#010101',
                valueColor: '#ff0000',
                titleFontSize: 14,
                valueFontSize: 14,
              },
              {
                value: '25.5%',
                title: '标题',
                titleColor: '#010101',
                valueColor: '#ff0000',
                titleFontSize: 14,
                valueFontSize: 14,
              },
            ],
            subName1: '25645',
            subName2: '',
            nameFontSize: '22px',
            subName1FontSize: '20px',
            subName2FontSize: '',
          },
        ],
      },
      {
        type: 'pcBarChart',
        icon: 'icon-tongji',
        title: '柱状图',
        api: {},
        search: {},
        header: {
          left: 'left',
          text: '柱状图',
          fontSize: '18px',
          fontColor: 'rgba(48, 49, 51, 1)',
          padding: '10px 5px',
          textAlign: 'left',
          borderBottom: '1px solid #efefef',
          margin: '0 0 10px',
        },
        content: {
          num1: 12512,
          num2: 0.1234,
          title: '订单统计信息',
          icon: 'fa fa-meetup',
          iconFontSize: 42,
          num2Color: '#FF6462',
          iconColor: 'rgba(64, 158, 255, 1)',
          iconBackgroundColor: 'rgba(64, 158, 255, 0.35)',
          iconBorderRadius: 40,
          iconPadding: 10,
          iconWidth: 60,
          iconHeight: 60,
        },
        style: {
          bgColor: null,
          bgMargin: null,
          fontSize: 14,
          maginTop: null,
          bgPadding: '0 16px 16px',
          boxShadow: true,
          borderRadius: 5,
          innerBgColor: 'rgba(255, 255, 255, 1)',
          innerBorderColor: 'rgba(241, 242, 243, 1)',
          innerBorderStyle: 'solid',
          innerBorderWidth: 1,
          gridHeight: '330px',
        },
        series: [
          {
            data: '10,41.1,30.4,65.1,53.3,53.3,53.3,41.1,30.4,65.1,53.3,10',
            name: '预购队列',
            emphasisFocus: 'series',
            itemStyleColor: 'rgba(254, 154, 139, 1)',
            lineStyleColor: 'rgba(254, 154, 139, 1)',
            areaStyleColor1: 'rgba(254, 154, 139, 0.7)',
            areaStyleColor2: 'rgba(254, 154, 139, 0.01)',
            itemStyleBorderColor: 'rgba(254, 154, 139, 1)',
            barWidth: '',
            borderRadius: '30,30,0,0',
            itemStyleColor1: 'rgba(250, 180, 101, 1)',
            itemStyleColor2: 'rgba(250, 180, 101, 0)',
          },
          {
            data: '0,24.1,7.2,15.5,42.4,42.4,42.4,24.1,7.2,15.5,42.4,0',
            name: '最新成交价',
            showEmphasis: true,
            itemStyleColor: 'rgba(158, 135, 255, 1)',
            lineStyleColor: 'rgba(158, 135, 255, 1)',
            areaStyleColor1: 'rgba(158, 135, 255, 0.7)',
            areaStyleColor2: 'rgba(158, 135, 255, 0.01)',
            itemStyleBorderColor: 'rgba(158, 135, 255, 1)',
            emphasisFocus: 'series',
            borderRadius: '30,30,0,0',
            itemStyleColor1: 'rgba(255, 120, 0, 1)',
            itemStyleColor2: 'rgba(255, 120, 0, 0)',
          },
        ],
        grid: {
          top: 70,
          left: 30,
          right: 30,
          bottom: 20,
        },
        xAxis: {
          data: '1月,2月,3月,4月,5月,6月,7月,8月,9月,10月,11月,12月',
        },
        yAxis: {
          name: '价格',
          type: 'value',
        },
        legend: {
          top: 'top',
          data: '房屋及结构物,专用设备,通用设备,文物和陈列品,图书、档案',
          left: '',
          type: 'scroll',
          right: '1%',
          orient: 'horizontal',
          itemWidth: 18,
          itemHeight: 13,
        },
        key: '1709022598000_27896',
        rules: [],
      },
      {
        type: 'pcLineChart',
        icon: 'icon-tongji1',
        api: {},
        search: {},
        grid: {
          top: 70,
          left: 30,
          right: 30,
          bottom: 20,
        },
        index: 6,
        rules: [],
        style: {
          bgColor: null,
          bgMargin: null,
          fontSize: 14,
          maginTop: null,
          bgPadding: '0 16px 16px',
          boxShadow: true,
          borderRadius: 5,
          innerBgColor: 'rgba(255, 255, 255, 1)',
          innerBorderColor: 'rgba(241, 242, 243, 1)',
          innerBorderStyle: 'solid',
          innerBorderWidth: 1,
        },
        title: '折线图',
        xAxis: {
          data: '1月,2月,3月,4月,5月,6月,7月,8月,9月,10月,11月,12月',
        },
        yAxis: {
          name: '价格',
          type: 'value',
        },
        legend: {
          top: 'top',
          data: '房屋及结构物,专用设备,通用设备,文物和陈列品,图书、档案',
          left: '',
          type: 'scroll',
          right: '1%',
          orient: 'horizontal',
          itemWidth: 18,
          itemHeight: 13,
        },
        series: [
          {
            data: '10,41.1,30.4,65.1,53.3,53.3,53.3,41.1,30.4,65.1,53.3,10',
            name: '预购队列',
            emphasisFocus: 'series',
            itemStyleColor: 'rgba(254, 154, 139, 1)',
            lineStyleColor: 'rgba(254, 154, 139, 1)',
            areaStyleColor1: 'rgba(254, 154, 139, 0.7)',
            areaStyleColor2: 'rgba(254, 154, 139, 0.01)',
            itemStyleBorderColor: 'rgba(254, 154, 139, 1)',
          },
          {
            data: '0,24.1,7.2,15.5,42.4,42.4,42.4,24.1,7.2,15.5,42.4,0',
            name: '最新成交价',
            showEmphasis: true,
            itemStyleColor: 'rgba(158, 135, 255, 1)',
            lineStyleColor: 'rgba(158, 135, 255, 1)',
            areaStyleColor1: 'rgba(158, 135, 255, 0.7)',
            areaStyleColor2: 'rgba(158, 135, 255, 0.01)',
            itemStyleBorderColor: 'rgba(158, 135, 255, 1)',
            emphasisFocus: 'series',
          },
        ],
        header: {
          left: 'left',
          text: '折线图',
          fontSize: '18px',
          fontColor: 'rgba(48, 49, 51, 1)',
          padding: '10px 5px',
          textAlign: 'left',
          borderBottom: '1px solid #efefef',
          margin: '0 0 10px',
        },
      },
      {
        type: 'pcLineBarChart',
        icon: 'icon-tongji',
        title: '组合图',
        api: {},
        search: {},
        header: {},
        content: {
          num1: 12512,
          num2: 0.1234,
          title: '订单统计信息',
          icon: 'fa fa-meetup',
          iconFontSize: 42,
          num2Color: '#FF6462',
          iconColor: 'rgba(64, 158, 255, 1)',
          iconBackgroundColor: 'rgba(64, 158, 255, 0.35)',
          iconBorderRadius: 40,
          iconPadding: 10,
          iconWidth: 60,
          iconHeight: 60,
        },
        style: {
          bgColor: null,
          bgMargin: null,
          fontSize: 14,
          maginTop: null,
          bgPadding: '16px',
          boxShadow: true,
          borderRadius: 5,
          innerBgColor: 'rgba(255, 255, 255, 1)',
          innerBorderColor: 'rgba(241, 242, 243, 1)',
          innerBorderStyle: 'solid',
          innerBorderWidth: 1,
        },
      },
      {
        type: 'pcPieChart',
        icon: 'icon-dingwei9',
        api: {},
        search: {},
        style: {
          bgColor: null,
          bgMargin: null,
          bgPadding: '0 16px',
          boxShadow: true,
          borderRadius: 5,
          innerBgColor: 'rgba(255, 255, 255, 1)',
          innerBorderColor: 'rgba(241, 242, 243, 1)',
          innerBorderStyle: 'solid',
          innerBorderWidth: 1,
        },
        title: '饼图',
        legend: {
          top: 'middle',
          data: '房屋及结构物,专用设备,通用设备,文物和陈列品,图书、档案',
          left: '65%',
          type: 'scroll',
          right: '',
          orient: 'vertical',
          itemWidth: 13,
          itemHeight: 13,
        },
        series: {
          data: '14.2,38.87,17.88,9.05,2.05',
          center: '39%,50%',
          radius: '102',
          showLabel: true,
        },
        header: {
          left: 'center',
          text: '饼图',
          fontSize: '18px',
          fontColor: 'rgba(48, 49, 51, 1)',
          borderBottom: '1px solid #efefef',
          padding: '10px 5px',
          margin: '0 0 10px',
        },
      },
      {
        type: 'pcRingChart',
        icon: 'icon-dingwei9',
        api: {},
        search: {},
        style: {
          bgColor: null,
          bgMargin: null,
          fontSize: 14,
          maginTop: null,
          bgPadding: '0 16px',
          boxShadow: true,
          borderRadius: 5,
          innerBgColor: 'rgba(255, 255, 255, 1)',
          innerBorderColor: 'rgba(241, 242, 243, 1)',
          innerBorderStyle: 'solid',
          innerBorderWidth: 1,
        },
        title: '环形图',
        legend: {
          top: 'middle',
          data: '房屋及结构物,专用设备,通用设备,文物和陈列品,图书、档案',
          right: '1%',
          itemWidth: 13,
          itemHeight: 13,
        },
        series: {
          data: '14.2,38.87,17.88,9.05,2.05',
          center: '39%,50%',
          radius: '102',
          radius0: '80',
          radius1: '110',
          padAngle: '3',
          showLabel: true,
          borderRadius: '5',
        },
        header: {
          left: 'center',
          text: '环形图',
          fontSize: '18px',
          fontColor: 'rgba(48, 49, 51, 1)',
          borderBottom: '1px solid #efefef',
          padding: '10px 5px',
          margin: '0 0 10px',
        },
      },
      {
        type: 'pcTable',
        title: '表格',
        icon: 'icon-calendar',
        api: {},
        search: {},
        style: {
          stripe: true,
          bgColor: null,
          bgMargin: null,
          fontSize: 14,
          maginTop: null,
          bgPadding: '0',
          boxShadow: true,
          borderRadius: 5,
          innerBgColor: null,
          innerBorderColor: null,
          innerBorderStyle: 'solid',
          innerBorderWidth: 1,
        },
        columns: [
          {
            prop: 'index',
            type: 'index',
            label: '#',
            width: '50',
            headerAlign: 'center',
            align: 'center',
          },
          {
            label: '日期',
            prop: 'date',
            width: '100',
            headerAlign: 'center',
            align: 'center',
            type: '',
          },
          {
            label: '姓名',
            prop: 'name',
            width: '100',
            type: '',
            align: 'center',
            headerAlign: 'center',
          },
          {
            label: '地址',
            prop: 'address',
            type: '',
            width: '',
            headerAlign: 'left',
            align: 'left',
          },
        ],
        options: {
          tableData: '[\n  {\n    "date": "2016-05-03",\n    "name": "Tom",\n    "address": "No. 189, Grove St, Los Angeles"\n  },\n  {\n    "date": "2016-05-02",\n    "name": "Tom",\n    "address": "No. 189, Grove St, Los Angeles"\n  },\n  {\n    "date": "2016-05-04",\n    "name": "Tom",\n    "address": "No. 189, Grove St, Los Angeles"\n  },\n  {\n    "date": "2016-05-01",\n    "name": "Tom",\n    "address": "No. 189, Grove St, Los Angeles"\n  }\n]',
        },
        header: {
          fontSize: '18px',
          text: '表格标题',
          fontColor: 'rgba(48, 49, 51, 1)',
          bgColor: 'rgba(255, 255, 255, 1)',
          padding: '5px 5px 10px',
          borderBottom: '1px solid #efefef',
          margin: '0 0 5px',
          textAlign: 'left',
        },
      },
    ],
  },
];
